# Specify version format
version: "1.0.0.{build}"

# Branches to build
branches:
  only: 
    - master

# Clone depth
clone_depth: 5

# Clone repository as zip archive
shallow_clone: true

# Including commits with 'build' comment
only_commits:
  message: build

# Build platform, i.e. Win32 (instead of x86), x64, Any CPU. This setting is optional.
platform: 
  - x86
  - x64

# Scripts that are called at very beginning, before repo cloning
init:
  - cmd: cmake --version
  - cmd: msbuild /version

# Scripts that run after cloning repository
install:
  - choco install doxygen.portable
  - choco install graphviz.portable
  - cmd: git config --global user.name "AppVeyor"
  - cmd: git config --global user.email "team@appveyor.com"
  - cmd: git config --global push.default simple
  - cmd: git submodule update --init --recursive --remote

# Build scripts
build_script:
  - cmd: cd scripts
  - cmd: if "%platform%"=="x86" 01-generate-VisualStudio-x32.bat
  - cmd: if "%platform%"=="x64" 01-generate-VisualStudio-x64.bat
  - cmd: 02-build-VisualStudio.bat
  - cmd: 03-tests.bat
  - cmd: 04-install-VisualStudio.bat
  - cmd: 05-doxygen-VisualStudio.bat
  - cmd: 06-clean.bat

# Test scripts
test: off
